#
# Configurações de acesso ao Minio
#
aws:
  s3:
    region: us-east-2
# When using AWS, the library will use one of the available
# credential sources described in the documentation.     
    accessKeyId: TEST
    secretAccessKey: TEST
    bucket: TEST
